services:
  - "mysql:5.5"
  - "postgres:alpine"

variables:
  MYSQL_ROOT_PASSWORD: my-secret-pw
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: my-secret-pw

before_script:
 - apk add --no-cache git
 - git submodule sync --recursive
 - git submodule update --init --recursive

.build_tpl: &build_tpl
  stage: build
  script:
   - export MYSQL_USER=root
   - export MYSQL_PASSWORD=my-secret-pw
   - npm install -q -g @openmicrostep/msbuildsystem.cli
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
   - msbuildsystem build -w dist/gitlab/ --target build --env gitlab --no-progress

build-8:
  <<: *build_tpl
  image: node:8-alpine

build-latest:
  <<: *build_tpl
  image: node:alpine

deploy:
  stage: deploy
  image: node:8-alpine
  only:
    - tags
  script:
   - echo "$NPM_AUTH" >> ~/.npmrc
   - npm install -q -g @openmicrostep/msbuildsystem.cli
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
   - msbuildsystem build -w dist/gitlab/ --target deploy --env gitlab --no-progress
