before_script:
 - npm set registry $NPM_REGISTRY

build:
  image: node:6-alpine
  stage: build
  script:
   - npm install -q -g @msbuildsystem/cli
   - msbuildsystem modules install @msbuildsystem/js.typescript @msbuildsystem/aspects
   - msbuildsystem build -w dist/
  artifacts:
    expire_in: 31d
    paths:
     - dist/

test:
  image: node:6-alpine
  stage: test
  dependencies:
   - build
  script:
   - npm install -q -g @microstep/tests
   - mstests dist/js/debug/node_modules/@microstep/aspects.tests/typescript/core/tst/core.spec.js 
             dist/js/debug/node_modules/@microstep/aspects.sequelize.tests/typescript/datasource.sequelize/tst/datasource.sequelize.spec.js

publish:
  image: node:6-alpine
  stage: deploy
  script:
    - echo "$NPM_AUTH" >> ~/.npmrc
    - npm publish dist/js/debug/node_modules/@microstep/aspects
    - npm publish dist/js/debug/node_modules/@microstep/aspects.express
    - npm publish dist/js/debug/node_modules/@microstep/aspects.sequelize
    - npm publish dist/js/debug/node_modules/@microstep/aspects.xhr
  dependencies:
   - build
  only:
    - master
  when: manual
  environment: production
