services:
  - "microsoft/mssql-server-linux:2017-GA"
  - "mysql"
  - "postgres:alpine"

variables:
  ACCEPT_EULA: "Y"
  SA_PASSWORD: "7wnjijM9JihtKok4RC6"
  MYSQL_ROOT_PASSWORD: "my-secret-pw"
  POSTGRES_PASSWORD: "my-secret-pw"

before_script:
 - apk add --no-cache git
 - git submodule sync --recursive
 - git submodule update --init --recursive

.build_tpl: &build_tpl
  stage: build
  script:
   - npm install -q -g @openmicrostep/msbuildsystem.cli
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
   - msbuildsystem build -w dist/gitlab/ --target build --env gitlab --no-progress

build-6:
  <<: *build_tpl
  image: node:6-alpine

build-8:
  <<: *build_tpl
  image: node:8-alpine

deploy:
  stage: deploy
  image: node:6-alpine
  only:
    - tags
  script:
   - echo "$NPM_AUTH" >> ~/.npmrc
   - npm install -q -g @openmicrostep/msbuildsystem.cli
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
   - msbuildsystem build -w dist/gitlab/ --target deploy --env gitlab --no-progress
