sudo: required
dist: trusty

language: node_js

services:
  - docker

before_install:  
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo wget -O /usr/local/bin/gitlab-runner https://gitlab-ci-multi-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-ci-multi-runner-linux-amd64
  - sudo chmod +x /usr/local/bin/gitlab-runner

matrix:
  include:
  - node_js: "6"
    script: /usr/local/bin/gitlab-runner exec docker --env TRAVIS=true --env TRAVIS_JOB_ID=${TRAVIS_JOB_ID} --env TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} --env TRAVIS_BRANCH=${TRAVIS_BRANCH} build-6
  - node_js: "8"
    script: /usr/local/bin/gitlab-runner exec docker --env TRAVIS=true --env TRAVIS_JOB_ID=${TRAVIS_JOB_ID} --env TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} --env TRAVIS_BRANCH=${TRAVIS_BRANCH} build-8
