language: node_js

node_js:
  - "8"
  - "latest"

services:
  - mysql
  - postgresql

script:
  - export MYSQL_HOST=localhost
  - export MYSQL_USER=root
  - export MYSQL_PASSWORD=
  - export POSTGRES_HOST=localhost
  - export POSTGRES_USER=postgres
  - export POSTGRES_PASSWORD=
  - npm install -q -g @openmicrostep/msbuildsystem.cli
  - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - msbuildsystem build -w dist/travis/ --target build --env travis --no-progress
