sudo: required

language: node_js

node_js:
  - "6"
  - "8"

services:
  - docker

before_install:  
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker-compose up -d
  - until docker exec aspects_mssql_1 /opt/mssql-tools/bin/sqlcmd -U sa -P 7wnjijM9JihtKok4RC6 -Q "EXEC sp_databases"; do >&2 echo "Postgres is unavailable - sleeping"; sleep 1; done

script:
  - npm install -q -g @openmicrostep/msbuildsystem.cli
  - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
  - git clone https://github.com/OpenMicroStep/MSBuildSystem.git
  - msbuildsystem build -w dist/travis/ --target build --env travis --no-progress
