mssql:
  image: microsoft/mssql-server-linux:2017-GA
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=7wnjijM9JihtKok4RC6
  ports:
   - 127.0.0.1:1433:1433
mysql:
  image: mysql
  environment: 
   - MYSQL_ROOT_PASSWORD=my-secret-pw
  ports:
   - 127.0.0.1:3306:3306
postgres:
  image: postgres:alpine
  environment: 
   - POSTGRES_PASSWORD=my-secret-pw
  ports:
   - 127.0.0.1:5432:5432
